#!/usr/bin/env python3
"""ADR 011 demo: content-provenance sealing as a model-collapse mitigation.

Two authors seal the origin of their content at creation time (hash only,
never the raw text); a crawler seals one ingestion decision per document.
The journal then proves what a plain crawler log cannot: that a later batch
INCLUDED a document whose hash was sealed as "ai-agent" EARLIER — recursive
training, hash-level, tamper-evident.
"""
from __future__ import annotations

import hashlib
import json
import sqlite3
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from noirebox.attestation import build_attestation
from noirebox.chain import KeyPair, verify_chain
from noirebox.store import EventStore

HUMAN_DRAFT = (
    "Field notes (human author): interview transcript, port of Le Havre, "
    "electric-fleet drivers — written 2026-09-27, no AI involved."
)
AGENT_OUTPUT = (
    "Blog post (ai-agent): \"5 reasons your fleet should go electric\" — "
    "generated by a writing assistant, published as-is."
)


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        db_path = f"{tmp}/demo.db"
        store = EventStore(db_path)
        key = KeyPair.load_or_create(f"{tmp}/demo.key")

        # [1] Creation-time sealing: the registry of declared origins.
        registry: dict[str, str] = {}
        for origin, content in (("human", HUMAN_DRAFT), ("ai-agent", AGENT_OUTPUT)):
            digest = sha256_hex(content)
            store.append("content_provenance", {"origin": origin, "content_hash": digest}, key)
            registry[digest] = origin
        print("[1] Two origins sealed at creation: one human draft, one ai-agent output.")

        # [2] One sealed decision per ingested document. The third document
        # comes from a legacy crawler that never consults the registry, so its
        # declared origin is "unknown" — yet the inclusion is sealed, and the
        # chain timestamps make that provable later.
        crawl = [
            ("batch-2026-09", sha256_hex(HUMAN_DRAFT), True),
            ("batch-2026-09", sha256_hex(AGENT_OUTPUT), True),
            ("batch-2026-10", sha256_hex(AGENT_OUTPUT), False),
        ]
        excluded_seq = None
        for batch, digest, consulted in crawl:
            declared = registry.get(digest, "unknown") if consulted else "unknown"
            decision = "exclude" if declared == "ai-agent" else "include"
            payload = {
                "batch": batch,
                "doc_hash": digest,
                "declared_origin": declared,
                "decision": decision,
                "reason": "registry lookup" if consulted else "legacy crawler: no lookup",
            }
            event = store.append("ingestion_decision", payload, key)
            if decision == "exclude":
                excluded_seq = event.seq
        print("[2] Three ingestion decisions sealed: include (human), exclude (ai-agent), include (unknown).")

        att = build_attestation(store, key)
        print(f"[3] Attestation: {att['total_events']} events, chain intact: {att['chain_valid']}.")

        # [4] The retroactive recursion proof: walk the journal, match every
        # INCLUDED document against earlier seals — the unknown-origin batch
        # carries a hash that was sealed as ai-agent before it was ingested.
        events = {e["seq"]: e for e in store.all()}
        seals = {e["payload"]["content_hash"]: e for e in events.values() if e["type"] == "content_provenance"}
        recursive = []
        for e in events.values():
            if e["type"] != "ingestion_decision" or e["payload"]["decision"] != "include":
                continue
            seal = seals.get(e["payload"]["doc_hash"])
            if seal and seal["payload"]["origin"] == "ai-agent":
                recursive.append((e, seal))
        assert len(recursive) == 1, "exactly the legacy-crawler case should be flagged"
        ingested, seal = recursive[0]
        print(f"[4] PROOF of recursive ingestion — event {ingested['seq']} (batch "
              f"{ingested['payload']['batch']}, decision include, declared origin "
              f"{ingested['payload']['declared_origin']}) carries the hash sealed as ai-agent at event "
              f"{seal['seq']}, sealed earlier ({seal['ts']} < {ingested['ts']}).")

        # [5] An operator rewrites the exclusion decision: the ai-agent
        # document now appears as an accepted part of the corpus.
        tampered = dict(events[excluded_seq]["payload"])
        tampered["decision"] = "include"
        conn = sqlite3.connect(db_path)
        conn.execute("UPDATE events SET payload = ? WHERE seq = ?",
                     (json.dumps(tampered, ensure_ascii=False, sort_keys=True), excluded_seq))
        conn.commit()
        conn.close()
        print(f"[5] The operator rewrites event {excluded_seq}: the ai-agent exclusion becomes \"include\".")

        report = verify_chain(key.public_hex(), store.all())
        assert not report["valid"], "the tampering should have been detected"
        err = report["first_error"]
        print(f"[✗] DETECTED — event {err['seq']}: {err['reason']}")
        print("    A third party running verifier/verifier.py on an export sees exactly this.")


if __name__ == "__main__":
    main()
